# Introduction to Tensorflow

The links to notebooks are in the youtube description
https://youtu.be/tPYj3fFJGjk

In [21]:
from IPython.daisplay import clear_output
!pip3 install tensorflow
clear_output()

In [3]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/home/chaudha4/.local/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


## Tensors

"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.



### Creating Tensors



In [4]:
num1 = tf.Variable(324, tf.int16)
flo1 = tf.Variable(3.567, tf.float64)

In [5]:
str1 = tf.Variable([["1", "2"],["this is a string", "and me"]], tf.string)
str1.shape

TensorShape([2, 2])

### Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar. 


In [6]:
tf.rank(num1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
tf.rank(str1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of Tensors
Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To **get the shape** of a tensor we use the shape attribute.


In [8]:
str1.shape

TensorShape([2, 2])

### Changing Shape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [47]:
t1 = tf.ones([2,4,5])
print(t1)
t1 = tf.random.uniform([2,4,5], minval=0, maxval=99, dtype=tf.dtypes.int32)
print(t1)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 4, 5), dtype=float32)
tf.Tensor(
[[[26 95 64 31 10]
  [79 29 16 57 23]
  [75 57  0 15 60]
  [32 49 55 56 43]]

 [[33 49 79 33 93]
  [ 0  1 44 46 25]
  [69 40 58 91 13]
  [20 19 88  0 91]]], shape=(2, 4, 5), dtype=int32)


In [48]:
t2 = tf.reshape(t1, [4, 2, -1])
print(t2)

tf.Tensor(
[[[26 95 64 31 10]
  [79 29 16 57 23]]

 [[75 57  0 15 60]
  [32 49 55 56 43]]

 [[33 49 79 33 93]
  [ 0  1 44 46 25]]

 [[69 40 58 91 13]
  [20 19 88  0 91]]], shape=(4, 2, 5), dtype=int32)


### Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```


In [49]:
# first row
print(t1[0])

tf.Tensor(
[[26 95 64 31 10]
 [79 29 16 57 23]
 [75 57  0 15 60]
 [32 49 55 56 43]], shape=(4, 5), dtype=int32)


In [50]:
# first 2nd element from 1st row
print(t1[0,1])

tf.Tensor([79 29 16 57 23], shape=(5,), dtype=int32)


In [54]:
# 2nd element from all rows
print(t1[:, 2])

tf.Tensor(
[[75 57  0 15 60]
 [69 40 58 91 13]], shape=(2, 5), dtype=int32)


In [56]:
print(t1[:, 2, 3])

tf.Tensor([15 91], shape=(2,), dtype=int32)


### Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

### Operations

In [12]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

# Broadcasting support
b = tf.add(a, 1)
print(b)

print(tf.multiply(a, 10))

print(a * b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [13]:
# Use NumPy values
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [15]:
# Obtain numpy value from a tensor:
print(a.numpy())

[[1 2]
 [3 4]]


### Dynamic control flow

In [20]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  print(counter.numpy())
  max_num = tf.convert_to_tensor(max_num)
  print(max_num.numpy())
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('FizzBuzz')
    elif int(num % 3) == 0:
      print('Fizz')
    elif int(num % 5) == 0:
      print('Buzz')
    else:
      print(num.numpy())
    counter += 1

fizzbuzz(15)

0
15
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
