# Neural Networks

A neural network is a network of neurons that are connected to each other. Generally the neural network will have an input layer, an output layer and one or more hidden layers. Every neuron is connected to all neurons in the subsequent layer and each connection has a weight while each neuron has a bias. The weights and bias are randomly assigned at initialization.

The network is then trained by tuning the weights and biases till we reach a point where a given input yields the expected output.

## Unsupervised Learning
If you want to extract patterns from a set of unlabelled data – then you use either a Restricted Boltzmann
Machine, or an autoencoder.

## Supervised Learning
If you have labeled data and you want to build a classifier, you have several different options depending on your application.

1. For text processing tasks like sentiment analysis, parsing, and named entity recognition – use a Recurrent Net or a Recursive Neural Tensor Network(RNTN).

1. For any language model that operates on the character level, use a Recurrent Net.

1. For image recognition, use a Deep Belief Network or a Convolutional Net.

1. For object recognition, use a Convolutional Net or an RNTN.

1. For speech recognition, use a Recurrent Net.

In general, Deep Belief Networks and Multilayer Perceptrons with rectified linear units – also known as RELU – are both good choices for classification. For time series analysis, it’s best to use a Recurrent Net.

In [4]:
import sys
import numpy as np
print("Python:", sys.version)
print("Numpy:", np.__version__)

Python: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
Numpy: 1.18.5


## Neural Network using python
We can build a simple Neural netowrk without using any frameworks like Tensorflow or pytorch. Lets try to do that using python

### Coding a layer

Lets say that you have 3 inputs to a neuron (these are ouputs from a previous layer, in this case that layer had 3 neurons). Each input will have a value and each connection will have a weight. To calculate the output of this neuron, we simply sum up the product if input value and weights. Finally we add the bias. See the example below

```
1.1-----.2------|~~~~|
2.1-----.9------| 4  |-----------> 5.27
1.2-----.7------|____|
```

In [2]:
inputs = [1.1, 2.1, 1.2]
weights = [0.2, 0.9, -0.7]
bias = 4

output = 0
for ii in range(len(inputs)):
    output += inputs[ii] * weights[ii]

output += bias

print(output)

5.2700000000000005


In [6]:
# numpy makes it even simpler. Realize that what we did above is called a dot product in maths !!
output = np.dot(inputs, weights) + bias
print(output)

5.2700000000000005


This process is done at every neuron. When the network is being trained, this process is repeated several times by adjust the weights and biases of all the neurons in the network to find an optimal setting where every training input delivers the traiing output. Once the model is trianed, then we can input a test data and see the results.


### Define Layer

Now lets define a Neuron Class and a Layer CLass. We will use these to build a model next.


In [6]:
import random
import numpy as np

class Neuron(object):
    def __init__(self, num_inputs):
        self.bias = random.randint(0,9)
        #self.weights = [random.random() for _ in range(num_inputs)]
        self.weights = np.random.randn(num_inputs)

    # for printing
    def __repr__(self):
        return f"Node bias is: {self.bias} and weight is: {self.weights}"


class Layer(object):
    def __init__(self, neurons):
        self.len = len(neurons)
        self.neurons = neurons
        self.outputs = None

    def forward(self, layer_inputs):
        self.outputs = [ np.dot(n.weights, layer_inputs) + n.bias for n in self.neurons ]
        return self.outputs


    

### Creating a Model
Lets create a model with two layers. The first layer has 3 neurons and 5 inputs. The second layer has just 1 neuron.

5 inputs --> layer 1(3 neurons)------>layer 2(1 neuron) ----> 1 output


In [5]:
NUM_NODES = 3
NUM_INPUTS = 5

# create 2 neurons each with 5 inputs
nodes = [Neuron(NUM_INPUTS) for ii in range(NUM_NODES)]
print(nodes[0])

# create input layer using these nodes. This layer will have 2 outputs since it has 2 nodes.
layer1 = Layer(nodes)

# lets create an output layer with just one neuron. Inputs in this layer is output from prev layer
nodes = [Neuron(layer1.len)]
layer2 = Layer(nodes)

# Test data
#ts_data = [random.random() for _ in range(NUM_INPUTS)]
ts_data = np.random.randn(NUM_INPUTS)

# Now feed the input thru layers.
print("Test Data:", ts_data)
print("Layer 1:", layer1.forward(ts_data))
print("layer 2:", layer2.forward(layer1.outputs))
print("-" * 30)

Node bias is: 1 and weight is: [1.6843625  1.02702216 1.88164117 1.17060424 0.19434945]
Test Data: [-0.72505057 -0.51609522 -1.43590574 -0.71248967  0.72229096]
Layer 1: [-4.146815159777426, 8.783391550848012, 8.753012652554899]
layer 2: [4.885304825861041]
------------------------------


### Activation Functions
Every neuron in hidden layers (and output layers) will also have an activation function with it that further changes the ouput from that neuron. Activation functions are mathematical equations that determine whether a neuron should be activated (“fired”) or not. They also help normalize the output of each neuron to a range between 1 and 0 or between -1 and 1.

1. Step Activation Function
1. Sigmoid Activation Function
1. (Rectified Linear Unit) Activation Function - Most commonly used.

No lets add an activation function to the previous model.

In [3]:
class Activation_ReLU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)
        return self.outputs

In [4]:
# Now feed the input thru layers applyling Activation funtion
act = Activation_ReLU()
print("Test Data:", ts_data)
print("Layer 1 :", layer1.forward(ts_data))
print("Layer 1 Activation:", act.forward(layer1.outputs))
print("layer 2:", layer2.forward(act.outputs))
print("Layer 2 Activation:", act.forward(layer2.outputs))
print("-" * 30)


Test Data: [ 1.23409924 -0.78939283  1.21321803 -0.79087021  1.64496744]
Layer 1: [5.088537886931036, -0.9620679361881948, 10.780068708298156]
Layer 1 Activation: [ 5.08853789  0.         10.78006871]
layer 2: [-5.593457901319399]
Layer 2 Activation: [0.]
------------------------------


This concludes a very basic indroduction to a neuran networks. There are frameworks available that make it easier to create and train models. One of such framework is Tensorflow that we look into next.

# Introduction to Tensorflow

The links to notebooks are in the youtube description
https://youtu.be/tPYj3fFJGjk

A good introduction is available in [google ML course](https://developers.google.com/machine-learning/crash-course/first-steps-with-tensorflow/toolkit)


In [21]:
from IPython.daisplay import clear_output
!pip3 install tensorflow
clear_output()

In [8]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/home/chaudha4/.local/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


## Tensors

A tensor is an object that can be represented as an array (i.e. a Vector in mathematics)

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.



### Creating Tensors



In [38]:
num1 = tf.Variable(324.1, dtype=tf.dtypes.float64)
print(num1)
num1 = tf.Variable([324, 122])
print(num1)
flo1 = tf.Variable([[3.567,2.13],[3.14, 1.12]], dtype=tf.dtypes.float32)
print(flo1)

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=324.1>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([324, 122], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[3.567, 2.13 ],
       [3.14 , 1.12 ]], dtype=float32)>


In [39]:
str1 = tf.Variable([["1", "2"],["this is a string", "and me"]], tf.string)
print(str1, str1.shape)


<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'1', b'2'],
       [b'this is a string', b'and me']], dtype=object)> (2, 2)


### Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar. 


In [47]:
tf.rank(num1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

AttributeError: 'ResourceVariable' object has no attribute 'rank'

In [41]:
tf.rank(str1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of Tensors
Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To **get the shape** of a tensor we use the shape attribute.


In [42]:
str1.shape

TensorShape([2, 2])

### Changing Shape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [51]:
t1 = tf.ones([2,4,5])
print(t1)
t1 = tf.random.uniform([2,4,5], minval=0,maxval=99, dtype=tf.dtypes.int32)
print(t1)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 4, 5), dtype=float32)
tf.Tensor(
[[[65 34 21 32 13]
  [80 17 97 22 74]
  [93 26 59 61 60]
  [52 53 49 20 83]]

 [[74 85 46 42 54]
  [35 63 60 11 65]
  [91 97 34 35 19]
  [ 6 81 70 40 11]]], shape=(2, 4, 5), dtype=int32)


In [48]:
t2 = tf.reshape(t1, [4, 2, -1])
print(t2)

tf.Tensor(
[[[26 95 64 31 10]
  [79 29 16 57 23]]

 [[75 57  0 15 60]
  [32 49 55 56 43]]

 [[33 49 79 33 93]
  [ 0  1 44 46 25]]

 [[69 40 58 91 13]
  [20 19 88  0 91]]], shape=(4, 2, 5), dtype=int32)


### Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```


In [49]:
# first row
print(t1[0])

tf.Tensor(
[[26 95 64 31 10]
 [79 29 16 57 23]
 [75 57  0 15 60]
 [32 49 55 56 43]], shape=(4, 5), dtype=int32)


In [50]:
# first 2nd element from 1st row
print(t1[0,1])

tf.Tensor([79 29 16 57 23], shape=(5,), dtype=int32)


In [54]:
# 2nd element from all rows
print(t1[:, 2])

tf.Tensor(
[[75 57  0 15 60]
 [69 40 58 91 13]], shape=(2, 5), dtype=int32)


In [56]:
print(t1[:, 2, 3])

tf.Tensor([15 91], shape=(2,), dtype=int32)


### Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

### Operations

In [12]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

# Broadcasting support
b = tf.add(a, 1)
print(b)

print(tf.multiply(a, 10))

print(a * b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [13]:
# Use NumPy values
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [15]:
# Obtain numpy value from a tensor:
print(a.numpy())

[[1 2]
 [3 4]]


# Regression vs. classification

A regression model predicts continuous values. For example, regression models make predictions that answer questions like the following:

    What is the value of a house in California?

    What is the probability that a user will click on this ad?

A classification model predicts discrete values. For example, classification models make predictions that answer questions like the following:

    Is a given email message spam or not spam?

    Is this an image of a dog, a cat, or a hamster?
