In [2]:
import numpy as np

In [9]:
# create a numpy array
a = np.array([1,2,3,4,5,6,7,8,9])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(9,)


In [8]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [10]:
# Start with index 0 and get every 2nd element
a[::2]

array([1, 3, 5, 7, 9])

In [4]:
# Start with index 1 and get every 2nd element till index 5(excluding)
a[1:5:2]

array([2, 4])

In [6]:
# Start with index end(-1) and get every 2nd element in reverse direction
a[-1::-2]

array([9, 7, 5, 3, 1])

In [27]:
# change the values in the 3rd column of both of the following Numpy arrays to 20
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)
a[:, 2] = 20
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]


In [18]:
b = np.random.random(9)
print(b)

[0.78547128 0.14893601 0.75783653 0.4718227  0.09595438 0.80039186
 0.35293457 0.6936336  0.76173534]


In [24]:
print(np.random.random((2,3,4)))

[[[0.25129664 0.88690654 0.85383808 0.99427024]
  [0.77210091 0.29143768 0.3675352  0.93274592]
  [0.68332929 0.96854482 0.23414458 0.60169013]]

 [[0.56536059 0.58524495 0.61751963 0.23414843]
  [0.33562316 0.95424863 0.65636502 0.68131345]
  [0.7216061  0.30873221 0.59410882 0.37097035]]]


In [36]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

a += 10
print(a)

print(np.arange(9))
print(np.arange(201,215))

a[np.arange(3), [2,2,2]] += 100
print(a)

print(a[a > 50])

[[2 3]
 [6 7]]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[0 1 2 3 4 5 6 7 8]
[201 202 203 204 205 206 207 208 209 210 211 212 213 214]
[[ 11  12 113  14]
 [ 15  16 117  18]
 [ 19  20 121  22]]
[113 117 121]


In [42]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
print(a)
print(np.max(a, axis=0))
b = np.max(a, axis=1).sum()
b

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]


15

In [12]:
# Reorganizing Arrays
before = np.array([[1,2,3,4],[6,7,8,9]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [6 7 8 9]]
[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [17]:
# Vertical stack
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
v3 = np.vstack([v1,v2])
print(v3)

v3 = np.hstack([v1, v2])
print(v3)

print(v1 + v2)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[5 7 9]


In [18]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x + v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
